### ISSUE TITLE
Issues with existing jQuery

### ISSUE THREAD

**Issue by debopamsengupta** [opencomponents/oc-client-browser#8]
We're having some issues with using `oc-client` on some of our pages which use different versions of  jQuery

Although the client checks for existing jQuery on the page, it just checks the `window.$` and uses `oc.require` to fetch jQuery anyway (but doesn't assign it) and this overrides `window.jQuery`

https://github.com/opencomponents/oc-client-browser/blob/master/src/oc-client.js#L332

I'm thinking, the checks can be extended to include `window.jQuery` as well as `window.$` and we can only use `oc.require` to fetch it if it doesn't exist on the page. Does that sound okay ?

cc @matteofigus @nickbalestra

**Comment by nickbalestra** [comment]
Sounds fair to me @debopamsengupta.
@mattiaerre do you have anything to add?

**Comment by nickbalestra** [comment]
Thanks again @debopamsengupta - 
Published on
- oc v0.40.4 (https://github.com/opentable/oc/releases)
- oc-client (node) v2.1.22 (https://github.com/opencomponents/oc-client-node/releases)
